import { buildCreatedFathomMeetingRecords } from "@/lib/fathom-ingest/meeting-builder";

describe("fathom-ingest/meeting-builder", () => {
  it("builds the meeting and planning session records for a new ingest", () => {
    const now = new Date("2026-07-02T10:30:00.000Z");
    const result = buildCreatedFathomMeetingRecords({
      now,
      meetingId: "meeting-1",
      planId: "plan-1",
      userId: "user-1",
      workspaceId: "workspace-1",
      connectionId: "connection-1",
      providerSourceId: "provider-1",
      meetingTitle: "Sprint Planning",
      meetingSummary: "Discussed roadmap",
      transcriptText: "Meeting transcript",
      startTime: new Date("2026-07-02T09:00:00.000Z"),
      endTime: new Date("2026-07-02T10:00:00.000Z"),
      durationSeconds: 3600,
      uniquePeople: [{ name: "Jane Doe", email: "jane@example.com", role: "attendee" }],
      finalizedTasks: [{ id: "task-1", title: "Prepare deck" }],
      sanitizedTasks: [{ id: "task-1", title: "Prepare deck" }],
      sanitizedTaskLevels: {
        light: [{ id: "task-1", title: "Prepare deck" }],
        medium: [{ id: "task-1", title: "Prepare deck" }],
        detailed: [{ id: "task-1", title: "Prepare deck" }],
      },
      analysisResult: {
        keyMoments: [{ timestamp: 10, label: "Intro" }],
        overallSentiment: "positive",
        speakerActivity: [{ speaker: "Jane", seconds: 42 }],
        meetingMetadata: { source: "fathom" },
      } as any,
      recordingIdHash: "recording-hash",
      candidateRecordingHashes: ["recording-hash", "legacy-hash"],
      dedupeFingerprints: ["title:sprint planning|t:123"],
      recordingUrl: "https://example.com/recording",
      shareUrl: "https://example.com/share",
      organizerEmail: "host@example.com",
    });

    expect(result.meeting).toMatchObject({
      _id: "meeting-1",
      userId: "user-1",
      workspaceId: "workspace-1",
      connectionId: "connection-1",
      providerSourceId: "provider-1",
      title: "Sprint Planning",
      originalTranscript: "Meeting transcript",
      summary: "Discussed roadmap",
      attendees: [{ name: "Jane Doe", email: "jane@example.com", role: "attendee" }],
      extractedTasks: [{ id: "task-1", title: "Prepare deck" }],
      originalAiTasks: [{ id: "task-1", title: "Prepare deck" }],
      allTaskLevels: {
        light: [{ id: "task-1", title: "Prepare deck" }],
        medium: [{ id: "task-1", title: "Prepare deck" }],
        detailed: [{ id: "task-1", title: "Prepare deck" }],
      },
      keyMoments: [{ timestamp: 10, label: "Intro" }],
      overallSentiment: "positive",
      speakerActivity: [{ speaker: "Jane", seconds: 42 }],
      meetingMetadata: { source: "fathom" },
      recordingIdHash: "recording-hash",
      recordingIdHashes: ["recording-hash", "legacy-hash"],
      dedupeFingerprints: ["title:sprint planning|t:123"],
      recordingUrl: "https://example.com/recording",
      shareUrl: "https://example.com/share",
      organizerEmail: "host@example.com",
      startTime: new Date("2026-07-02T09:00:00.000Z"),
      endTime: new Date("2026-07-02T10:00:00.000Z"),
      duration: 3600,
      ingestSource: "fathom",
      state: "tasks_ready",
      analysisAttemptedAt: now,
      completionAuditAttemptedAt: now,
      completionAuditModel: expect.any(String),
      completionAuditSuggestionCount: 0,
      createdAt: now,
      lastActivityAt: now,
      planningSessionId: "plan-1",
    });

    expect(result.planningSession).toMatchObject({
      _id: "plan-1",
      userId: "user-1",
      workspaceId: "workspace-1",
      connectionId: "connection-1",
      providerSourceId: "provider-1",
      title: 'Plan from "Sprint Planning"',
      inputText: "Discussed roadmap",
      extractedTasks: [{ id: "task-1", title: "Prepare deck" }],
      originalAiTasks: [{ id: "task-1", title: "Prepare deck" }],
      allTaskLevels: {
        light: [{ id: "task-1", title: "Prepare deck" }],
        medium: [{ id: "task-1", title: "Prepare deck" }],
        detailed: [{ id: "task-1", title: "Prepare deck" }],
      },
      sourceMeetingId: "meeting-1",
      meetingMetadata: { source: "fathom" },
      createdAt: now,
      lastActivityAt: now,
    });
  });
});
